### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by Datou** [StartHua/ComfyUI_OOTDiffusion_CXH#1]
win11
python 11.7
torch 2.2.0+cu118

---

Total VRAM 24563 MB, total RAM 65451 MB
xformers version: 0.0.24+cu118
Set vram state to: NORMAL_VRAM
Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
VAE dtype: torch.bfloat16
Using xformers cross attention
Traceback (most recent call last):
  File "D:\ComfyUI\.venv\Lib\site-packages\torch\utils\cpp_extension.py", line 2096, in _run_ninja_build
    subprocess.run(
  File "C:\Users\doggi\AppData\Local\Programs\Python\Python311\Lib\subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['ninja', '-v']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\ComfyUI\nodes.py", line 1887, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\__init__.py", line 1, in <module>
    from .OodGenerater import Ood_hd_CXH
  File "D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\OodGenerater.py", line 6, in <module>
    from .preprocess.humanparsing.aigc_run_parsing import Parsing
  File "D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\preprocess\humanparsing\aigc_run_parsing.py", line 7, in <module>
    from .parsing_api import load_atr_model, load_lip_model, inference
  File "D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\preprocess\humanparsing\parsing_api.py", line 11, in <module>
    from . import networks
  File "D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\preprocess\humanparsing\networks\__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\preprocess\humanparsing\networks\__init__.py", line 2, in <module>
    from networks.AugmentCE2P import resnet101
  File "D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\preprocess\humanparsing\networks\AugmentCE2P.py", line 22, in <module>
    from modules import InPlaceABNSync
  File "D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\preprocess\humanparsing\modules\__init__.py", line 1, in <module>
    from .bn import ABN, InPlaceABN, InPlaceABNSync
  File "D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\preprocess\humanparsing\modules\bn.py", line 10, in <module>
    from .functions import *
  File "D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH\preprocess\humanparsing\modules\functions.py", line 11, in <module>
    _backend = load(name="inplace_abn",
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\ComfyUI\.venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1306, in load
    return _jit_compile(
           ^^^^^^^^^^^^^
  File "D:\ComfyUI\.venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1710, in _jit_compile
    _write_ninja_file_and_build_library(
  File "D:\ComfyUI\.venv\Lib\site-packages\torch\utils\cpp_extension.py", line 1823, in _write_ninja_file_and_build_library
    _run_ninja_build(
  File "D:\ComfyUI\.venv\Lib\site-packages\torch\utils\cpp_extension.py", line 2112, in _run_ninja_build
    raise RuntimeError(message) from e
RuntimeError: Error building extension 'inplace_abn': [1/1] "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin/link.exe" inplace_abn.o inplace_abn_cpu.o inplace_abn_cuda.cuda.o inplace_abn_cuda_half.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:D:\ComfyUI\.venv\Lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\ComfyUI\.venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:inplace_abn.pyd
FAILED: inplace_abn.pyd
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin/link.exe" inplace_abn.o inplace_abn_cpu.o inplace_abn_cuda.cuda.o inplace_abn_cuda_half.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:D:\ComfyUI\.venv\Lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\ComfyUI\.venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:inplace_abn.pyd
  正在创建库 inplace_abn.lib 和对象 inplace_abn.exp
MSVCRT.lib(loadcfg.obj) : error LNK2001: 无法解析的外部符号 __enclave_config
MSVCRT.lib(loadcfg.obj) : error LNK2001: 无法解析的外部符号 __guard_eh_cont_table
MSVCRT.lib(loadcfg.obj) : error LNK2001: 无法解析的外部符号 __guard_eh_cont_count
MSVCRT.lib(loadcfg.obj) : error LNK2001: 无法解析的外部符号 __volatile_metadata
inplace_abn.pyd : fatal error LNK1120: 4 个无法解析的外部命令
ninja: build stopped: subcommand failed.

Cannot import D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH module for custom nodes: Error building extension 'inplace_abn': [1/1] "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin/link.exe" inplace_abn.o inplace_abn_cpu.o inplace_abn_cuda.cuda.o inplace_abn_cuda_half.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:D:\ComfyUI\.venv\Lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\ComfyUI\.venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:inplace_abn.pyd
FAILED: inplace_abn.pyd
"C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\bin/link.exe" inplace_abn.o inplace_abn_cpu.o inplace_abn_cuda.cuda.o inplace_abn_cuda_half.cuda.o /nologo /DLL c10.lib c10_cuda.lib torch_cpu.lib torch_cuda.lib -INCLUDE:?warp_size@cuda@at@@YAHXZ torch.lib /LIBPATH:D:\ComfyUI\.venv\Lib\site-packages\torch\lib torch_python.lib /LIBPATH:D:\ComfyUI\.venv\Scripts\libs "/LIBPATH:C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.8\lib\x64" cudart.lib /out:inplace_abn.pyd
  正在创建库 inplace_abn.lib 和对象 inplace_abn.exp
MSVCRT.lib(loadcfg.obj) : error LNK2001: 无法解析的外部符号 __enclave_config
MSVCRT.lib(loadcfg.obj) : error LNK2001: 无法解析的外部符号 __guard_eh_cont_table
MSVCRT.lib(loadcfg.obj) : error LNK2001: 无法解析的外部符号 __guard_eh_cont_count
MSVCRT.lib(loadcfg.obj) : error LNK2001: 无法解析的外部符号 __volatile_metadata
inplace_abn.pyd : fatal error LNK1120: 4 个无法解析的外部命令
ninja: build stopped: subcommand failed.

Import times for custom nodes:
   5.2 seconds (IMPORT FAILED): D:\ComfyUI\custom_nodes\ComfyUI_OOTDiffusion_CXH

---

D:\ComfyUI>pip list
Package            Version
------------------ ------------
accelerate         0.27.2
aiohttp            3.9.3
aiosignal          1.3.1
attrs              23.2.0
certifi            2022.12.7
charset-normalizer 2.1.1
colorama           0.4.6
contourpy          1.2.0
cycler             0.12.1
diffusers          0.24.0
einops             0.7.0
filelock           3.9.0
fonttools          4.49.0
frozenlist         1.4.1
fsspec             2024.2.0
huggingface-hub    0.20.3
idna               3.4
imageio            2.34.0
importlib-metadata 7.0.1
Jinja2             3.1.2
kiwisolver         1.4.5
lazy_loader        0.3
MarkupSafe         2.1.3
matplotlib         3.8.3
mpmath             1.3.0
multidict          6.0.5
networkx           3.2.1
ninja              1.11.1.1
numpy              1.26.3
opencv-python      4.9.0.80
packaging          23.2
pillow             10.2.0
pip                24.0
psutil             5.9.8
pyparsing          3.1.1
python-dateutil    2.8.2
PyYAML             6.0.1
regex              2023.12.25
requests           2.28.1
safetensors        0.4.2
scikit-image       0.22.0
scipy              1.12.0
setuptools         65.5.0
six                1.16.0
sympy              1.12
tifffile           2024.2.12
tokenizers         0.15.2
torch              2.2.0+cu118
torchaudio         2.2.0+cu118
torchsde           0.2.6
torchvision        0.17.0+cu118
tqdm               4.66.2
trampoline         0.1.2
transformers       4.38.1
typing_extensions  4.8.0
urllib3            1.26.13
xformers           0.0.24+cu118
yarl               1.9.4
zipp               3.17.0

**Comment by Datou** [comment]
解决了，先打开x64 Native Tools Command Prompt for VS 2022，然后在这个终端里启动comfyui，编译很快就完成了。

**Comment by ziziguai** [comment]
> 解决了，先打开x64 Native Tools Command Prompt for VS 2022，然后在这个终端里启动comfyui，编译很快就完成了。

同样的报错，x64重新编译了还是不行

**Comment by wsry888** [comment]
用x64 Native Tools Command Prompt for VS 2022启动的，报错这个：CUDA_HOME environment variable is not set. Please set it to your CUDA install root.
